name: Deploy

on:
  push:
    branches:
      - master
      - refactor

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create env file
        run: |
          touch .env
          echo NEXT_PUBLIC_GOOGLE_LOCATION_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_LOCATION_API_KEY }} >> .env
          echo NODE_ENV=production >> .env
          echo DATABASE_URL=mongodb://aaaaa:bbbb@1.2.3.4:5555/cccc?authSource=dddd
          cat .env
      - name: Expose branch name as an env variable
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jana19/treelative-client:${{ env.BRANCH }}
      - name: Redeploy on Portainer
        uses: wei/curl@master
        with:
          args: -X POST ${{ secrets.DEPLOY_CLIENT }}
